import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import Header from '@/components/Header'
config.autoAddCss = false  // 防止图标闪烁


const pingfang = localFont({
  src: '/fonts/PingFangSC-Medium.woff2',
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Gmoonlight1-幸好你也喜欢秋天",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pingfang.className}>
      <body>   
        <Header navTitle={metadata.title} />
        {children}
      </body>
    </html>
  );
}
