import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false  // 防止图标闪烁


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Gmoonlight1-幸好你也喜欢秋天",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
